// Package genesiscloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package genesiscloud

import (
	"time"
)

const (
	GenesiscloudScopes = "genesiscloud.Scopes"
)

// Defines values for ComputeV1ImageType.
const (
	ComputeV1ImageTypeBaseOs        ComputeV1ImageType = "base-os"
	ComputeV1ImageTypePreconfigured ComputeV1ImageType = "preconfigured"
	ComputeV1ImageTypeSnapshot      ComputeV1ImageType = "snapshot"
)

var AllComputeV1ImageTypes = []ComputeV1ImageType{
	ComputeV1ImageTypeBaseOs,
	ComputeV1ImageTypePreconfigured,
	ComputeV1ImageTypeSnapshot,
}

// Defines values for ComputeV1InstanceAction.
const (
	ComputeV1InstanceActionStart ComputeV1InstanceAction = "start"
	ComputeV1InstanceActionStop  ComputeV1InstanceAction = "stop"
)

var AllComputeV1InstanceActions = []ComputeV1InstanceAction{
	ComputeV1InstanceActionStart,
	ComputeV1InstanceActionStop,
}

// Defines values for ComputeV1InstancePublicIPType.
const (
	ComputeV1InstancePublicIPTypeDynamic ComputeV1InstancePublicIPType = "dynamic"
	ComputeV1InstancePublicIPTypeStatic  ComputeV1InstancePublicIPType = "static"
)

var AllComputeV1InstancePublicIPTypes = []ComputeV1InstancePublicIPType{
	ComputeV1InstancePublicIPTypeDynamic,
	ComputeV1InstancePublicIPTypeStatic,
}

// Defines values for ComputeV1InstanceStatus.
const (
	ComputeV1InstanceStatusActive     ComputeV1InstanceStatus = "active"
	ComputeV1InstanceStatusCreating   ComputeV1InstanceStatus = "creating"
	ComputeV1InstanceStatusDeleting   ComputeV1InstanceStatus = "deleting"
	ComputeV1InstanceStatusEnqueued   ComputeV1InstanceStatus = "enqueued"
	ComputeV1InstanceStatusError      ComputeV1InstanceStatus = "error"
	ComputeV1InstanceStatusRestarting ComputeV1InstanceStatus = "restarting"
	ComputeV1InstanceStatusShutoff    ComputeV1InstanceStatus = "shutoff"
	ComputeV1InstanceStatusStarting   ComputeV1InstanceStatus = "starting"
	ComputeV1InstanceStatusStopping   ComputeV1InstanceStatus = "stopping"
)

var AllComputeV1InstanceStatuss = []ComputeV1InstanceStatus{
	ComputeV1InstanceStatusActive,
	ComputeV1InstanceStatusCreating,
	ComputeV1InstanceStatusDeleting,
	ComputeV1InstanceStatusEnqueued,
	ComputeV1InstanceStatusError,
	ComputeV1InstanceStatusRestarting,
	ComputeV1InstanceStatusShutoff,
	ComputeV1InstanceStatusStarting,
	ComputeV1InstanceStatusStopping,
}

// Defines values for ComputeV1InstanceType.
const (
	ComputeV1InstanceTypeVcpu12Memory24gDisk80g              ComputeV1InstanceType = "vcpu-12_memory-24g_disk-80g"
	ComputeV1InstanceTypeVcpu12Memory36gDisk80gNvidia1080ti3 ComputeV1InstanceType = "vcpu-12_memory-36g_disk-80g_nvidia1080ti-3"
	ComputeV1InstanceTypeVcpu12Memory36gDisk80gNvidia3060ti3 ComputeV1InstanceType = "vcpu-12_memory-36g_disk-80g_nvidia3060ti-3"
	ComputeV1InstanceTypeVcpu12Memory36gDisk80gNvidia30803   ComputeV1InstanceType = "vcpu-12_memory-36g_disk-80g_nvidia3080-3"
	ComputeV1InstanceTypeVcpu12Memory72gDisk80gNvidia30903   ComputeV1InstanceType = "vcpu-12_memory-72g_disk-80g_nvidia3090-3"
	ComputeV1InstanceTypeVcpu16Memory32gDisk80g              ComputeV1InstanceType = "vcpu-16_memory-32g_disk-80g"
	ComputeV1InstanceTypeVcpu16Memory48gDisk80gNvidia1080ti4 ComputeV1InstanceType = "vcpu-16_memory-48g_disk-80g_nvidia1080ti-4"
	ComputeV1InstanceTypeVcpu16Memory48gDisk80gNvidia3060ti4 ComputeV1InstanceType = "vcpu-16_memory-48g_disk-80g_nvidia3060ti-4"
	ComputeV1InstanceTypeVcpu16Memory48gDisk80gNvidia30804   ComputeV1InstanceType = "vcpu-16_memory-48g_disk-80g_nvidia3080-4"
	ComputeV1InstanceTypeVcpu16Memory64gDisk80gNvidia30802   ComputeV1InstanceType = "vcpu-16_memory-64g_disk-80g_nvidia3080-2"
	ComputeV1InstanceTypeVcpu16Memory96gDisk80gNvidia30902   ComputeV1InstanceType = "vcpu-16_memory-96g_disk-80g_nvidia3090-2"
	ComputeV1InstanceTypeVcpu16Memory96gDisk80gNvidia30904   ComputeV1InstanceType = "vcpu-16_memory-96g_disk-80g_nvidia3090-4"
	ComputeV1InstanceTypeVcpu20Memory120gDisk80gNvidia30905  ComputeV1InstanceType = "vcpu-20_memory-120g_disk-80g_nvidia3090-5"
	ComputeV1InstanceTypeVcpu20Memory40gDisk80g              ComputeV1InstanceType = "vcpu-20_memory-40g_disk-80g"
	ComputeV1InstanceTypeVcpu20Memory60gDisk80gNvidia1080ti5 ComputeV1InstanceType = "vcpu-20_memory-60g_disk-80g_nvidia1080ti-5"
	ComputeV1InstanceTypeVcpu20Memory60gDisk80gNvidia3060ti5 ComputeV1InstanceType = "vcpu-20_memory-60g_disk-80g_nvidia3060ti-5"
	ComputeV1InstanceTypeVcpu20Memory60gDisk80gNvidia30805   ComputeV1InstanceType = "vcpu-20_memory-60g_disk-80g_nvidia3080-5"
	ComputeV1InstanceTypeVcpu24Memory144gDisk80gNvidia30903  ComputeV1InstanceType = "vcpu-24_memory-144g_disk-80g_nvidia3090-3"
	ComputeV1InstanceTypeVcpu24Memory144gDisk80gNvidia30906  ComputeV1InstanceType = "vcpu-24_memory-144g_disk-80g_nvidia3090-6"
	ComputeV1InstanceTypeVcpu24Memory48gDisk80g              ComputeV1InstanceType = "vcpu-24_memory-48g_disk-80g"
	ComputeV1InstanceTypeVcpu24Memory72gDisk80gNvidia1080ti6 ComputeV1InstanceType = "vcpu-24_memory-72g_disk-80g_nvidia1080ti-6"
	ComputeV1InstanceTypeVcpu24Memory72gDisk80gNvidia3060ti6 ComputeV1InstanceType = "vcpu-24_memory-72g_disk-80g_nvidia3060ti-6"
	ComputeV1InstanceTypeVcpu24Memory72gDisk80gNvidia30806   ComputeV1InstanceType = "vcpu-24_memory-72g_disk-80g_nvidia3080-6"
	ComputeV1InstanceTypeVcpu24Memory96gDisk80gNvidia30803   ComputeV1InstanceType = "vcpu-24_memory-96g_disk-80g_nvidia3080-3"
	ComputeV1InstanceTypeVcpu28Memory168gDisk80gNvidia30907  ComputeV1InstanceType = "vcpu-28_memory-168g_disk-80g_nvidia3090-7"
	ComputeV1InstanceTypeVcpu28Memory84gDisk80gNvidia1080ti7 ComputeV1InstanceType = "vcpu-28_memory-84g_disk-80g_nvidia1080ti-7"
	ComputeV1InstanceTypeVcpu28Memory84gDisk80gNvidia3060ti7 ComputeV1InstanceType = "vcpu-28_memory-84g_disk-80g_nvidia3060ti-7"
	ComputeV1InstanceTypeVcpu28Memory84gDisk80gNvidia30807   ComputeV1InstanceType = "vcpu-28_memory-84g_disk-80g_nvidia3080-7"
	ComputeV1InstanceTypeVcpu2Memory4gDisk80g                ComputeV1InstanceType = "vcpu-2_memory-4g_disk-80g"
	ComputeV1InstanceTypeVcpu2Memory8gDisk80gAmdrx4704       ComputeV1InstanceType = "vcpu-2_memory-8g_disk-80g_amdrx470-4"
	ComputeV1InstanceTypeVcpu2Memory8gDisk80gAmdrx4705       ComputeV1InstanceType = "vcpu-2_memory-8g_disk-80g_amdrx470-5"
	ComputeV1InstanceTypeVcpu2Memory8gDisk80gAmdrx4706       ComputeV1InstanceType = "vcpu-2_memory-8g_disk-80g_amdrx470-6"
	ComputeV1InstanceTypeVcpu2Memory8gDisk80gAmdrx4707       ComputeV1InstanceType = "vcpu-2_memory-8g_disk-80g_amdrx470-7"
	ComputeV1InstanceTypeVcpu2Memory8gDisk80gAmdrx4708       ComputeV1InstanceType = "vcpu-2_memory-8g_disk-80g_amdrx470-8"
	ComputeV1InstanceTypeVcpu32Memory128gDisk80gNvidia30804  ComputeV1InstanceType = "vcpu-32_memory-128g_disk-80g_nvidia3080-4"
	ComputeV1InstanceTypeVcpu32Memory192gDisk80gNvidia30904  ComputeV1InstanceType = "vcpu-32_memory-192g_disk-80g_nvidia3090-4"
	ComputeV1InstanceTypeVcpu32Memory192gDisk80gNvidia30908  ComputeV1InstanceType = "vcpu-32_memory-192g_disk-80g_nvidia3090-8"
	ComputeV1InstanceTypeVcpu32Memory96gDisk80gNvidia1080ti8 ComputeV1InstanceType = "vcpu-32_memory-96g_disk-80g_nvidia1080ti-8"
	ComputeV1InstanceTypeVcpu32Memory96gDisk80gNvidia3060ti8 ComputeV1InstanceType = "vcpu-32_memory-96g_disk-80g_nvidia3060ti-8"
	ComputeV1InstanceTypeVcpu32Memory96gDisk80gNvidia30808   ComputeV1InstanceType = "vcpu-32_memory-96g_disk-80g_nvidia3080-8"
	ComputeV1InstanceTypeVcpu4Memory12gDisk80gNvidia1080ti1  ComputeV1InstanceType = "vcpu-4_memory-12g_disk-80g_nvidia1080ti-1"
	ComputeV1InstanceTypeVcpu4Memory12gDisk80gNvidia3060ti1  ComputeV1InstanceType = "vcpu-4_memory-12g_disk-80g_nvidia3060ti-1"
	ComputeV1InstanceTypeVcpu4Memory12gDisk80gNvidia30801    ComputeV1InstanceType = "vcpu-4_memory-12g_disk-80g_nvidia3080-1"
	ComputeV1InstanceTypeVcpu4Memory24gDisk80gNvidia30901    ComputeV1InstanceType = "vcpu-4_memory-24g_disk-80g_nvidia3090-1"
	ComputeV1InstanceTypeVcpu4Memory8gDisk80g                ComputeV1InstanceType = "vcpu-4_memory-8g_disk-80g"
	ComputeV1InstanceTypeVcpu8Memory16gDisk80g               ComputeV1InstanceType = "vcpu-8_memory-16g_disk-80g"
	ComputeV1InstanceTypeVcpu8Memory24gDisk80gNvidia1080ti2  ComputeV1InstanceType = "vcpu-8_memory-24g_disk-80g_nvidia1080ti-2"
	ComputeV1InstanceTypeVcpu8Memory24gDisk80gNvidia3060ti2  ComputeV1InstanceType = "vcpu-8_memory-24g_disk-80g_nvidia3060ti-2"
	ComputeV1InstanceTypeVcpu8Memory24gDisk80gNvidia30802    ComputeV1InstanceType = "vcpu-8_memory-24g_disk-80g_nvidia3080-2"
	ComputeV1InstanceTypeVcpu8Memory32gDisk80gNvidia30801    ComputeV1InstanceType = "vcpu-8_memory-32g_disk-80g_nvidia3080-1"
	ComputeV1InstanceTypeVcpu8Memory48gDisk80gNvidia30901    ComputeV1InstanceType = "vcpu-8_memory-48g_disk-80g_nvidia3090-1"
	ComputeV1InstanceTypeVcpu8Memory48gDisk80gNvidia30902    ComputeV1InstanceType = "vcpu-8_memory-48g_disk-80g_nvidia3090-2"
)

var AllComputeV1InstanceTypes = []ComputeV1InstanceType{
	ComputeV1InstanceTypeVcpu12Memory24gDisk80g,
	ComputeV1InstanceTypeVcpu12Memory36gDisk80gNvidia1080ti3,
	ComputeV1InstanceTypeVcpu12Memory36gDisk80gNvidia3060ti3,
	ComputeV1InstanceTypeVcpu12Memory36gDisk80gNvidia30803,
	ComputeV1InstanceTypeVcpu12Memory72gDisk80gNvidia30903,
	ComputeV1InstanceTypeVcpu16Memory32gDisk80g,
	ComputeV1InstanceTypeVcpu16Memory48gDisk80gNvidia1080ti4,
	ComputeV1InstanceTypeVcpu16Memory48gDisk80gNvidia3060ti4,
	ComputeV1InstanceTypeVcpu16Memory48gDisk80gNvidia30804,
	ComputeV1InstanceTypeVcpu16Memory64gDisk80gNvidia30802,
	ComputeV1InstanceTypeVcpu16Memory96gDisk80gNvidia30902,
	ComputeV1InstanceTypeVcpu16Memory96gDisk80gNvidia30904,
	ComputeV1InstanceTypeVcpu20Memory120gDisk80gNvidia30905,
	ComputeV1InstanceTypeVcpu20Memory40gDisk80g,
	ComputeV1InstanceTypeVcpu20Memory60gDisk80gNvidia1080ti5,
	ComputeV1InstanceTypeVcpu20Memory60gDisk80gNvidia3060ti5,
	ComputeV1InstanceTypeVcpu20Memory60gDisk80gNvidia30805,
	ComputeV1InstanceTypeVcpu24Memory144gDisk80gNvidia30903,
	ComputeV1InstanceTypeVcpu24Memory144gDisk80gNvidia30906,
	ComputeV1InstanceTypeVcpu24Memory48gDisk80g,
	ComputeV1InstanceTypeVcpu24Memory72gDisk80gNvidia1080ti6,
	ComputeV1InstanceTypeVcpu24Memory72gDisk80gNvidia3060ti6,
	ComputeV1InstanceTypeVcpu24Memory72gDisk80gNvidia30806,
	ComputeV1InstanceTypeVcpu24Memory96gDisk80gNvidia30803,
	ComputeV1InstanceTypeVcpu28Memory168gDisk80gNvidia30907,
	ComputeV1InstanceTypeVcpu28Memory84gDisk80gNvidia1080ti7,
	ComputeV1InstanceTypeVcpu28Memory84gDisk80gNvidia3060ti7,
	ComputeV1InstanceTypeVcpu28Memory84gDisk80gNvidia30807,
	ComputeV1InstanceTypeVcpu2Memory4gDisk80g,
	ComputeV1InstanceTypeVcpu2Memory8gDisk80gAmdrx4704,
	ComputeV1InstanceTypeVcpu2Memory8gDisk80gAmdrx4705,
	ComputeV1InstanceTypeVcpu2Memory8gDisk80gAmdrx4706,
	ComputeV1InstanceTypeVcpu2Memory8gDisk80gAmdrx4707,
	ComputeV1InstanceTypeVcpu2Memory8gDisk80gAmdrx4708,
	ComputeV1InstanceTypeVcpu32Memory128gDisk80gNvidia30804,
	ComputeV1InstanceTypeVcpu32Memory192gDisk80gNvidia30904,
	ComputeV1InstanceTypeVcpu32Memory192gDisk80gNvidia30908,
	ComputeV1InstanceTypeVcpu32Memory96gDisk80gNvidia1080ti8,
	ComputeV1InstanceTypeVcpu32Memory96gDisk80gNvidia3060ti8,
	ComputeV1InstanceTypeVcpu32Memory96gDisk80gNvidia30808,
	ComputeV1InstanceTypeVcpu4Memory12gDisk80gNvidia1080ti1,
	ComputeV1InstanceTypeVcpu4Memory12gDisk80gNvidia3060ti1,
	ComputeV1InstanceTypeVcpu4Memory12gDisk80gNvidia30801,
	ComputeV1InstanceTypeVcpu4Memory24gDisk80gNvidia30901,
	ComputeV1InstanceTypeVcpu4Memory8gDisk80g,
	ComputeV1InstanceTypeVcpu8Memory16gDisk80g,
	ComputeV1InstanceTypeVcpu8Memory24gDisk80gNvidia1080ti2,
	ComputeV1InstanceTypeVcpu8Memory24gDisk80gNvidia3060ti2,
	ComputeV1InstanceTypeVcpu8Memory24gDisk80gNvidia30802,
	ComputeV1InstanceTypeVcpu8Memory32gDisk80gNvidia30801,
	ComputeV1InstanceTypeVcpu8Memory48gDisk80gNvidia30901,
	ComputeV1InstanceTypeVcpu8Memory48gDisk80gNvidia30902,
}

// Defines values for ComputeV1PlacementOption.
const (
	ComputeV1PlacementOptionA    ComputeV1PlacementOption = "A"
	ComputeV1PlacementOptionAUTO ComputeV1PlacementOption = "AUTO"
	ComputeV1PlacementOptionB    ComputeV1PlacementOption = "B"
)

var AllComputeV1PlacementOptions = []ComputeV1PlacementOption{
	ComputeV1PlacementOptionA,
	ComputeV1PlacementOptionAUTO,
	ComputeV1PlacementOptionB,
}

// Defines values for ComputeV1Region.
const (
	ComputeV1RegionARCISHAF1  ComputeV1Region = "ARC-IS-HAF-1"
	ComputeV1RegionNORDNOKRS1 ComputeV1Region = "NORD-NO-KRS-1"
)

var AllComputeV1Regions = []ComputeV1Region{
	ComputeV1RegionARCISHAF1,
	ComputeV1RegionNORDNOKRS1,
}

// Defines values for ComputeV1SecurityGroupRuleDirection.
const (
	ComputeV1SecurityGroupRuleDirectionEgress  ComputeV1SecurityGroupRuleDirection = "egress"
	ComputeV1SecurityGroupRuleDirectionIngress ComputeV1SecurityGroupRuleDirection = "ingress"
)

var AllComputeV1SecurityGroupRuleDirections = []ComputeV1SecurityGroupRuleDirection{
	ComputeV1SecurityGroupRuleDirectionEgress,
	ComputeV1SecurityGroupRuleDirectionIngress,
}

// Defines values for ComputeV1SecurityGroupRuleProtocol.
const (
	ComputeV1SecurityGroupRuleProtocolAll  ComputeV1SecurityGroupRuleProtocol = "all"
	ComputeV1SecurityGroupRuleProtocolIcmp ComputeV1SecurityGroupRuleProtocol = "icmp"
	ComputeV1SecurityGroupRuleProtocolTcp  ComputeV1SecurityGroupRuleProtocol = "tcp"
	ComputeV1SecurityGroupRuleProtocolUdp  ComputeV1SecurityGroupRuleProtocol = "udp"
)

var AllComputeV1SecurityGroupRuleProtocols = []ComputeV1SecurityGroupRuleProtocol{
	ComputeV1SecurityGroupRuleProtocolAll,
	ComputeV1SecurityGroupRuleProtocolIcmp,
	ComputeV1SecurityGroupRuleProtocolTcp,
	ComputeV1SecurityGroupRuleProtocolUdp,
}

// Defines values for ComputeV1SecurityGroupStatus.
const (
	ComputeV1SecurityGroupStatusCreated  ComputeV1SecurityGroupStatus = "created"
	ComputeV1SecurityGroupStatusCreating ComputeV1SecurityGroupStatus = "creating"
	ComputeV1SecurityGroupStatusDeleting ComputeV1SecurityGroupStatus = "deleting"
	ComputeV1SecurityGroupStatusEnqueued ComputeV1SecurityGroupStatus = "enqueued"
	ComputeV1SecurityGroupStatusError    ComputeV1SecurityGroupStatus = "error"
	ComputeV1SecurityGroupStatusUpdating ComputeV1SecurityGroupStatus = "updating"
)

var AllComputeV1SecurityGroupStatuss = []ComputeV1SecurityGroupStatus{
	ComputeV1SecurityGroupStatusCreated,
	ComputeV1SecurityGroupStatusCreating,
	ComputeV1SecurityGroupStatusDeleting,
	ComputeV1SecurityGroupStatusEnqueued,
	ComputeV1SecurityGroupStatusError,
	ComputeV1SecurityGroupStatusUpdating,
}

// Defines values for ComputeV1SnapshotStatus.
const (
	ComputeV1SnapshotStatusAvailable    ComputeV1SnapshotStatus = "available"
	ComputeV1SnapshotStatusError        ComputeV1SnapshotStatus = "error"
	ComputeV1SnapshotStatusSnapshotting ComputeV1SnapshotStatus = "snapshotting"
)

var AllComputeV1SnapshotStatuss = []ComputeV1SnapshotStatus{
	ComputeV1SnapshotStatusAvailable,
	ComputeV1SnapshotStatusError,
	ComputeV1SnapshotStatusSnapshotting,
}

// Defines values for ComputeV1VolumeStatus.
const (
	ComputeV1VolumeStatusActive   ComputeV1VolumeStatus = "active"
	ComputeV1VolumeStatusCreating ComputeV1VolumeStatus = "creating"
	ComputeV1VolumeStatusError    ComputeV1VolumeStatus = "error"
)

var AllComputeV1VolumeStatuss = []ComputeV1VolumeStatus{
	ComputeV1VolumeStatusActive,
	ComputeV1VolumeStatusCreating,
	ComputeV1VolumeStatusError,
}

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// ComputeV1AvailabilityResponse response
type ComputeV1AvailabilityResponse struct {
	Availability struct {
		InstanceTypes []struct {
			Available *bool `json:"available,omitempty"`

			// Type The instance type identifier.
			Type *ComputeV1InstanceType `json:"type,omitempty"`
		} `json:"instance_types"`
		Placement string `json:"placement"`

		// Region The region identifier.
		Region ComputeV1Region `json:"region"`
		Type   string          `json:"type"`
	} `json:"availability"`
}

// ComputeV1CreateInstanceResponse response
type ComputeV1CreateInstanceResponse struct {
	Instance ComputeV1Instance `json:"instance"`
}

// ComputeV1CreateSecurityGroupResponse response
type ComputeV1CreateSecurityGroupResponse struct {
	SecurityGroup ComputeV1SecurityGroup `json:"security_group"`
}

// ComputeV1Error defines model for compute.v1.Error.
type ComputeV1Error struct {
	// Code The Genesis Cloud error code.
	// Check the [developer documentation](https://developers.com/#error-codes) for more information on error codes.
	Code string `json:"code"`

	// Message An explanation of what went wrong.
	Message string `json:"message"`
}

// ComputeV1GetInstanceResponse response
type ComputeV1GetInstanceResponse struct {
	Instance ComputeV1Instance `json:"instance"`
}

// ComputeV1GetSecurityGroupResponse response
type ComputeV1GetSecurityGroupResponse struct {
	SecurityGroup ComputeV1SecurityGroup `json:"security_group"`
}

// ComputeV1GetSnapshotResponse response
type ComputeV1GetSnapshotResponse struct {
	Snapshot ComputeV1Snapshot `json:"snapshot"`
}

// ComputeV1GetVolumeResponse response
type ComputeV1GetVolumeResponse struct {
	Volume ComputeV1Volume `json:"volume"`
}

// ComputeV1Image defines model for compute.v1.Image.
type ComputeV1Image struct {
	CreatedAt Timestamp `json:"created_at"`

	// Id A unique number that can be used to identify and reference a specific image.
	Id ComputeV1ImageId `json:"id"`

	// Name The display name that has been given to an image. This is what is shown in the control panel and is generally a descriptive title for the image in question.
	Name string `json:"name"`

	// Regions The list of regions in which this image can be used in.
	Regions []ComputeV1Region `json:"regions"`

	// Type Describes the kind of image.
	Type ComputeV1ImageType `json:"type"`
}

// ComputeV1ImageType Describes the kind of image.
type ComputeV1ImageType string

// ComputeV1ImageId A unique number that can be used to identify and reference a specific image.
type ComputeV1ImageId = string

// ComputeV1Instance defines model for compute.v1.Instance.
type ComputeV1Instance struct {
	CreatedAt Timestamp `json:"created_at"`

	// Hostname The hostname of your instance.
	Hostname ComputeV1InstanceHostname `json:"hostname"`

	// Id The unique ID of the instance.
	Id string `json:"id"`

	// Image The image of the instance.
	Image struct {
		// Id A unique number that can be used to identify and reference a specific image.
		Id *ComputeV1ImageId `json:"id,omitempty"`

		// Name The image name.
		Name *string `json:"name,omitempty"`
	} `json:"image"`

	// Name The human-readable name set for the instance.
	Name ComputeV1InstanceName `json:"name"`

	// PlacementOption The placement option identifier.
	PlacementOption ComputeV1PlacementOption `json:"placement_option"`

	// PrivateIp The private IPv4 IP-Address (IPv4 address).
	PrivateIp string `json:"private_ip"`

	// PublicIp The public IPv4 IP-Address (IPv4 address).
	PublicIp string `json:"public_ip"`

	// PublicIpType When set to `static`, the instance's public IP will not change between start and stop actions.
	PublicIpType ComputeV1InstancePublicIPType `json:"public_ip_type"`

	// Region The region identifier.
	Region ComputeV1Region `json:"region"`

	// SecurityGroups The security groups of the instance.
	SecurityGroups []struct {
		// Id The security group ID.
		Id *ComputeV1InstanceSecurityGroupId `json:"id,omitempty"`

		// Name The name of the security group.
		Name *string `json:"name,omitempty"`
	} `json:"security_groups"`

	// SshKeys The ssh keys of the instance.
	SshKeys []struct {
		// Id The ssh key ID.
		Id *ComputeV1InstanceSSHKeyId `json:"id,omitempty"`

		// Name The name of the ssh key.
		Name *string `json:"name,omitempty"`
	} `json:"ssh_keys"`

	// Status The instance status
	Status ComputeV1InstanceStatus `json:"status"`

	// Type The instance type identifier.
	Type      ComputeV1InstanceType `json:"type"`
	UpdatedAt Timestamp             `json:"updated_at"`

	// Volumes The volumes of the instance
	Volumes []struct {
		// Id A unique identifier for each volume. This is automatically generated.
		Id *ComputeV1VolumeId `json:"id,omitempty"`

		// Name The volume name.
		Name *string `json:"name,omitempty"`
	} `json:"volumes"`
}

// ComputeV1InstanceAction defines model for compute.v1.Instance.Action.
type ComputeV1InstanceAction string

// ComputeV1InstanceCreateSnapshotResponse response
type ComputeV1InstanceCreateSnapshotResponse struct {
	Snapshot ComputeV1Snapshot `json:"snapshot"`
}

// ComputeV1InstanceHostname The hostname of your instance.
type ComputeV1InstanceHostname = string

// ComputeV1InstanceIsProtected Specifies if the instance is termination protected.
// When set to `true`, it"s not possible to destroy the instance until it"s switched to `false`.
// Set to `true` automatically for long-term billed instances.
type ComputeV1InstanceIsProtected = bool

// ComputeV1InstanceListActionsResponse response
type ComputeV1InstanceListActionsResponse struct {
	Actions []ComputeV1InstanceAction `json:"actions"`
}

// ComputeV1InstanceName The human-readable name set for the instance.
type ComputeV1InstanceName = string

// ComputeV1InstancePublicIPType When set to `static`, the instance's public IP will not change between start and stop actions.
type ComputeV1InstancePublicIPType string

// ComputeV1InstanceSSHKeyId The ssh key ID.
type ComputeV1InstanceSSHKeyId = string

// ComputeV1InstanceSecurityGroupId The security group ID.
type ComputeV1InstanceSecurityGroupId = string

// ComputeV1InstanceSecurityGroupIds An array of security group ids.
// **Please Note**: By default the **standard security group** is set if you don"t specify any Security Groups.
// You can override this behavior by providing a different Security Group.
type ComputeV1InstanceSecurityGroupIds = []ComputeV1InstanceSecurityGroupId

// ComputeV1InstanceStatus The instance status
type ComputeV1InstanceStatus string

// ComputeV1InstanceType The instance type identifier.
type ComputeV1InstanceType string

// ComputeV1ListImagesResponse response
type ComputeV1ListImagesResponse struct {
	Images     []ComputeV1Image `json:"images"`
	Page       int              `json:"page"`
	PerPage    int              `json:"per_page"`
	TotalCount int              `json:"total_count"`
}

// ComputeV1ListInstancesResponse response
type ComputeV1ListInstancesResponse struct {
	Instances  []ComputeV1Instance `json:"instances"`
	Page       int                 `json:"page"`
	PerPage    int                 `json:"per_page"`
	TotalCount int                 `json:"total_count"`
}

// ComputeV1ListSSHKeysResponse response
type ComputeV1ListSSHKeysResponse struct {
	Page       int               `json:"page"`
	PerPage    int               `json:"per_page"`
	SshKeys    []ComputeV1SSHKey `json:"ssh_keys"`
	TotalCount int               `json:"total_count"`
}

// ComputeV1ListSecurityGroupsResponse response
type ComputeV1ListSecurityGroupsResponse struct {
	Page           int                      `json:"page"`
	PerPage        int                      `json:"per_page"`
	SecurityGroups []ComputeV1SecurityGroup `json:"security_groups"`
	TotalCount     int                      `json:"total_count"`
}

// ComputeV1ListSnapshotsResponse response
type ComputeV1ListSnapshotsResponse struct {
	Page       int                 `json:"page"`
	PerPage    int                 `json:"per_page"`
	Snapshots  []ComputeV1Snapshot `json:"snapshots"`
	TotalCount int                 `json:"total_count"`
}

// ComputeV1ListVolumesResponse response
type ComputeV1ListVolumesResponse struct {
	Page       int               `json:"page"`
	PerPage    int               `json:"per_page"`
	TotalCount int               `json:"total_count"`
	Volumes    []ComputeV1Volume `json:"volumes"`
}

// ComputeV1PlacementOption The placement option identifier.
type ComputeV1PlacementOption string

// ComputeV1Region The region identifier.
type ComputeV1Region string

// ComputeV1SSHKey defines model for compute.v1.SSHKey.
type ComputeV1SSHKey struct {
	CreatedAt Timestamp `json:"created_at"`

	// Fingerprint The fingerprint of the SSH key.
	Fingerprint string `json:"fingerprint"`

	// Id A unique identifier for each SSH key. This is automatically generated.
	Id string `json:"id"`

	// Name The human-readable name for the SSH key.
	Name string `json:"name"`

	// Size The length of the SSH key.
	Size int `json:"size"`

	// Type The encryption algorithm type of the SSH key.
	Type string `json:"type"`

	// Value SSH public key.
	Value string `json:"value"`
}

// ComputeV1SecurityGroup defines model for compute.v1.SecurityGroup.
type ComputeV1SecurityGroup struct {
	CreatedAt Timestamp `json:"created_at"`

	// Description The human-readable description for the security group.
	Description string `json:"description"`

	// Id A unique identifier for each security group. This is automatically generated.
	Id string `json:"id"`

	// Name The human-readable name for the security group.
	Name string `json:"name"`

	// Region The region identifier.
	Region ComputeV1Region              `json:"region"`
	Rules  []ComputeV1SecurityGroupRule `json:"rules"`

	// Status The security group status.
	Status ComputeV1SecurityGroupStatus `json:"status"`
}

// ComputeV1SecurityGroupRule defines model for compute.v1.SecurityGroup.Rule.
type ComputeV1SecurityGroupRule struct {
	// Direction The direction of the rule.
	Direction ComputeV1SecurityGroupRuleDirection `json:"direction"`

	// PortRangeMax The maximum port number of the rule.
	PortRangeMax *int `json:"port_range_max,omitempty"`

	// PortRangeMin The minimum port number of the rule.
	PortRangeMin *int `json:"port_range_min,omitempty"`

	// Protocol The protocol of the rule.
	Protocol ComputeV1SecurityGroupRuleProtocol `json:"protocol"`
}

// ComputeV1SecurityGroupRuleDirection The direction of the rule.
type ComputeV1SecurityGroupRuleDirection string

// ComputeV1SecurityGroupRuleProtocol The protocol of the rule.
type ComputeV1SecurityGroupRuleProtocol string

// ComputeV1SecurityGroupStatus The security group status.
type ComputeV1SecurityGroupStatus string

// ComputeV1Snapshot defines model for compute.v1.Snapshot.
type ComputeV1Snapshot struct {
	CreatedAt Timestamp `json:"created_at"`

	// Id A unique identifier for each snapshot. This is automatically generated.
	Id string `json:"id"`

	// Name The human-readable name for the snapshot.
	Name string `json:"name"`

	// Region The region identifier.
	Region ComputeV1Region `json:"region"`

	// ResourceId The id of the resource (e.g. instance) that was snapshotted.
	ResourceId string `json:"resource_id"`

	// Size The storage size of this snapshot given in bytes.
	Size *string `json:"size,omitempty"`

	// Status The snapshot status.
	Status ComputeV1SnapshotStatus `json:"status"`
}

// ComputeV1SnapshotStatus The snapshot status.
type ComputeV1SnapshotStatus string

// ComputeV1UpdateInstanceResponse response
type ComputeV1UpdateInstanceResponse struct {
	Instance ComputeV1Instance `json:"instance"`
}

// ComputeV1UpdateSecurityGroupResponse response
type ComputeV1UpdateSecurityGroupResponse struct {
	SecurityGroup ComputeV1SecurityGroup `json:"security_group"`
}

// ComputeV1UpdateSnapshotResponse response
type ComputeV1UpdateSnapshotResponse struct {
	Snapshot ComputeV1Snapshot `json:"snapshot"`
}

// ComputeV1UpdateVolumeResponse response
type ComputeV1UpdateVolumeResponse struct {
	Volume ComputeV1Volume `json:"volume"`
}

// ComputeV1Volume defines model for compute.v1.Volume.
type ComputeV1Volume struct {
	CreatedAt Timestamp `json:"created_at"`

	// Description The human-readable description for the volume.
	Description string `json:"description"`

	// Id A unique identifier for each volume. This is automatically generated.
	Id ComputeV1VolumeId `json:"id"`

	// Instances The attached instances.
	Instances []struct {
		// Id The id of the attached instance.
		Id *string `json:"id,omitempty"`

		// Name The name of the attached instance.
		Name *string `json:"name,omitempty"`
	} `json:"instances"`

	// Name The human-readable name for the volume.
	Name string `json:"name"`

	// Region The region identifier.
	Region ComputeV1Region `json:"region"`

	// Size The storage size of this volume given in GiB.
	Size   int                   `json:"size"`
	Status ComputeV1VolumeStatus `json:"status"`
}

// ComputeV1VolumeStatus defines model for compute.v1.Volume.Status.
type ComputeV1VolumeStatus string

// ComputeV1VolumeId A unique identifier for each volume. This is automatically generated.
type ComputeV1VolumeId = string

// PageQueryParameter A positive integer to choose the page to return.
type PageQueryParameter = int

// PerPageQueryParameter A positive integer lower or equal to 100 to select the number of items to return.
type PerPageQueryParameter = int

// Error defines model for Error.
type Error = ComputeV1Error

// ListImagesParams defines parameters for ListImages.
type ListImagesParams struct {
	Page    *PageQueryParameter    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageQueryParameter `form:"per_page,omitempty" json:"per_page,omitempty"`
	Type    *ComputeV1ImageType    `form:"type,omitempty" json:"type,omitempty"`
}

// ListInstancesParams defines parameters for ListInstances.
type ListInstancesParams struct {
	Page    *PageQueryParameter    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageQueryParameter `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// CreateInstanceJSONBody defines parameters for CreateInstance.
type CreateInstanceJSONBody struct {
	// Hostname The hostname of your instance.
	Hostname ComputeV1InstanceHostname `json:"hostname"`

	// Image A unique number that can be used to identify and reference a specific image.
	Image ComputeV1ImageId `json:"image"`

	// IsProtected Specifies if the instance is termination protected.
	// When set to `true`, it"s not possible to destroy the instance until it"s switched to `false`.
	// Set to `true` automatically for long-term billed instances.
	IsProtected *ComputeV1InstanceIsProtected `json:"is_protected,omitempty"`

	// Metadata Option to provide metadata. Currently supported is `startup_script`.
	Metadata *struct {
		// StartupScript A plain text bash script or "cloud-config" file that will be executed after the first instance boot.
		// It is limited to 64 KiB in size. You can use it to configure your instance, e.g. installing the **NVIDIA GPU driver**.
		// Learn more about [startup scripts and installing the GPU driver](https://support.com/support/solutions/articles/47001122478).
		StartupScript *string `json:"startup_script,omitempty"`
	} `json:"metadata,omitempty"`

	// Name The human-readable name set for the instance.
	Name ComputeV1InstanceName `json:"name"`

	// Password The password to access the instance.
	// Your password must have upper and lower chars, digits and length between 8-72.
	// **Please Note**: Only one of `ssh_keys` or `password` can be provided.
	// Password is less secure - we recommend you use an SSH key-pair.
	Password *string `json:"password,omitempty"`

	// PlacementOption The placement option identifier.
	PlacementOption *ComputeV1PlacementOption `json:"placement_option,omitempty"`

	// PublicIpType When set to `static`, the instance's public IP will not change between start and stop actions.
	PublicIpType *ComputeV1InstancePublicIPType `json:"public_ip_type,omitempty"`

	// Region The region identifier.
	Region *ComputeV1Region `json:"region,omitempty"`

	// SecurityGroups An array of security group ids.
	// **Please Note**: By default the **standard security group** is set if you don"t specify any Security Groups.
	// You can override this behavior by providing a different Security Group.
	SecurityGroups *ComputeV1InstanceSecurityGroupIds `json:"security_groups,omitempty"`

	// SshKeys An array of ssh key ids.
	// This should not be provided if `password` authentication method is desired.
	SshKeys *[]ComputeV1InstanceSSHKeyId `json:"ssh_keys,omitempty"`

	// Type The instance type identifier.
	Type ComputeV1InstanceType `json:"type"`

	// Volumes An array of volume ids.
	Volumes *[]ComputeV1VolumeId `json:"volumes,omitempty"`
}

// UpdateInstanceJSONBody defines parameters for UpdateInstance.
type UpdateInstanceJSONBody struct {
	// IsProtected Specifies if the instance is termination protected.
	// When set to `true`, it"s not possible to destroy the instance until it"s switched to `false`.
	// Set to `true` automatically for long-term billed instances.
	IsProtected *ComputeV1InstanceIsProtected `json:"is_protected,omitempty"`

	// Name The human-readable name set for the instance.
	Name *ComputeV1InstanceName `json:"name,omitempty"`

	// SecurityGroups An array of security group ids.
	// **Please Note**: By default the **standard security group** is set if you don"t specify any Security Groups.
	// You can override this behavior by providing a different Security Group.
	SecurityGroups *ComputeV1InstanceSecurityGroupIds `json:"security_groups,omitempty"`

	// Volumes The instance's volumes IDs.
	Volumes *[]ComputeV1VolumeId `json:"volumes,omitempty"`
}

// InstanceActionJSONBody defines parameters for InstanceAction.
type InstanceActionJSONBody struct {
	Action *ComputeV1InstanceAction `json:"action,omitempty"`
}

// ListInstanceSnapshotsParams defines parameters for ListInstanceSnapshots.
type ListInstanceSnapshotsParams struct {
	Page    *PageQueryParameter    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageQueryParameter `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// CreateSnapshotJSONBody defines parameters for CreateSnapshot.
type CreateSnapshotJSONBody struct {
	// Name Name of the snapshot
	Name string `json:"name"`
}

// ListSecurityGroupsParams defines parameters for ListSecurityGroups.
type ListSecurityGroupsParams struct {
	Page    *PageQueryParameter    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageQueryParameter `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// CreateSecurityGroupJSONBody defines parameters for CreateSecurityGroup.
type CreateSecurityGroupJSONBody struct {
	// Description he human-readable description set for the security group.
	Description *string `json:"description,omitempty"`

	// Name The human-readable name set for the security group. **Please Note**: `default` and `standard` are not allowed names (reserved words).
	Name string `json:"name"`

	// Region The region identifier.
	Region *ComputeV1Region `json:"region,omitempty"`

	// Rules The list of rules of the security group.
	Rules []ComputeV1SecurityGroupRule `json:"rules"`
}

// UpdateSecurityGroupJSONBody defines parameters for UpdateSecurityGroup.
type UpdateSecurityGroupJSONBody struct {
	// Description he human-readable description set for the security group.
	Description *string `json:"description,omitempty"`

	// Name The human-readable name set for the security group.
	Name string `json:"name"`

	// Rules The list of rules of the security group.
	Rules []ComputeV1SecurityGroupRule `json:"rules"`
}

// ListSnapshotsParams defines parameters for ListSnapshots.
type ListSnapshotsParams struct {
	Page    *PageQueryParameter    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageQueryParameter `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// UpdateSnapshotJSONBody defines parameters for UpdateSnapshot.
type UpdateSnapshotJSONBody struct {
	// Name The new human-readable name for your snapshot.
	Name string `json:"name"`
}

// ListSSHKeysParams defines parameters for ListSSHKeys.
type ListSSHKeysParams struct {
	Page    *PageQueryParameter    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageQueryParameter `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// CreateSSHKeyJSONBody defines parameters for CreateSSHKey.
type CreateSSHKeyJSONBody struct {
	// Name The human-readable name for your ssh key.
	Name string `json:"name"`

	// Value SSH public key
	Value string `json:"value"`
}

// UpdateSSHKeyJSONBody defines parameters for UpdateSSHKey.
type UpdateSSHKeyJSONBody struct {
	// Name The new human-readable name for your ssh key.
	Name string `json:"name"`
}

// ListVolumesParams defines parameters for ListVolumes.
type ListVolumesParams struct {
	Page    *PageQueryParameter    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageQueryParameter `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// CreateVolumeJSONBody defines parameters for CreateVolume.
type CreateVolumeJSONBody struct {
	// Description The human-readable description set for the volume.
	Description string `json:"description"`

	// Name The human-readable name set for the volume.
	Name string `json:"name"`

	// Region The region identifier.
	Region *ComputeV1Region `json:"region,omitempty"`

	// Size The storage size of this volume given in GiB (Min: 1GiB).
	Size int `json:"size"`
}

// UpdateVolumeJSONBody defines parameters for UpdateVolume.
type UpdateVolumeJSONBody struct {
	// Description The human-readable description set for the volume.
	Description string `json:"description"`

	// Name The human-readable name set for the volume.
	Name string `json:"name"`
}

// CreateInstanceJSONRequestBody defines body for CreateInstance for application/json ContentType.
type CreateInstanceJSONRequestBody CreateInstanceJSONBody

// UpdateInstanceJSONRequestBody defines body for UpdateInstance for application/json ContentType.
type UpdateInstanceJSONRequestBody UpdateInstanceJSONBody

// InstanceActionJSONRequestBody defines body for InstanceAction for application/json ContentType.
type InstanceActionJSONRequestBody InstanceActionJSONBody

// CreateSnapshotJSONRequestBody defines body for CreateSnapshot for application/json ContentType.
type CreateSnapshotJSONRequestBody CreateSnapshotJSONBody

// CreateSecurityGroupJSONRequestBody defines body for CreateSecurityGroup for application/json ContentType.
type CreateSecurityGroupJSONRequestBody CreateSecurityGroupJSONBody

// UpdateSecurityGroupJSONRequestBody defines body for UpdateSecurityGroup for application/json ContentType.
type UpdateSecurityGroupJSONRequestBody UpdateSecurityGroupJSONBody

// UpdateSnapshotJSONRequestBody defines body for UpdateSnapshot for application/json ContentType.
type UpdateSnapshotJSONRequestBody UpdateSnapshotJSONBody

// CreateSSHKeyJSONRequestBody defines body for CreateSSHKey for application/json ContentType.
type CreateSSHKeyJSONRequestBody CreateSSHKeyJSONBody

// UpdateSSHKeyJSONRequestBody defines body for UpdateSSHKey for application/json ContentType.
type UpdateSSHKeyJSONRequestBody UpdateSSHKeyJSONBody

// CreateVolumeJSONRequestBody defines body for CreateVolume for application/json ContentType.
type CreateVolumeJSONRequestBody CreateVolumeJSONBody

// UpdateVolumeJSONRequestBody defines body for UpdateVolume for application/json ContentType.
type UpdateVolumeJSONRequestBody UpdateVolumeJSONBody
