package: genesiscloud
generate:
  models: true
output: ../types.gen.go # relative to codegen.go
output-options:
  user-templates:
    # extended from https://github.com/oapi-codegen/oapi-codegen/blob/fd1f9b3e448846c1c4749f5c7eaae60e2be7a02c/pkg/codegen/templates/constants.tmpl
    constants.tmpl: |
      {{- if gt (len .SecuritySchemeProviderNames) 0 }}
      const (
      {{range $ProviderName := .SecuritySchemeProviderNames}}
          {{- $ProviderName | sanitizeGoIdentity | ucFirst}}Scopes = "{{$ProviderName}}.Scopes"
      {{end}}
      )
      {{end}}
      {{range $Enum := .EnumDefinitions}}
      // Defines values for {{$Enum.TypeName}}.
      const (
      {{range $name, $value := $Enum.GetValues}}
        {{$name}} {{$Enum.TypeName}} = {{$Enum.ValueWrapper}}{{$value}}{{$Enum.ValueWrapper -}}
      {{end}}
      )
      var All{{$Enum.TypeName}}s = []{{$Enum.TypeName}}{
      {{range $name, $value := $Enum.GetValues -}}
        {{$name}},
      {{end}}
      }
      {{end}}

compatibility:
  always-prefix-enum-values: true
